service: find-food-truck

provider:
  name: aws
  runtime: nodejs18.x   # or a newer version if you prefer
  stage: dev            # you can change this (e.g., to 'prod')
  region: eu-west-1     # choose your preferred region
  environment:
    API_KEY: ${env:API_KEY}
    API_SECRET: ${env:API_SECRET}
    APP_URL: ${env:APP_URL}
    CLOUD_NAME: ${env:CLOUD_NAME}
    MONGODB: ${env:MONGODB}
    NODEMAILER_PASS: ${env:NODEMAILER_PASS}
    NODEMAILER_USER: ${env:NODEMAILER_USER}
    PORT: ${env:PORT}
    SECRET_KEY: ${env:SECRET_KEY}
functions:
  app:
    handler: index.handler   # points to the exported Lambda handler in index.js
    events:
      - http: 
          path: /
          method: any
          cors: true
          allowCredentials: false
      - http: 
          path: /{proxy+}
          method: any
          cors: true
          allowCredentials: false
plugins:
  # - serverless-offline
  - serverless-dotenv-plugin

custom:
  serverless-offline:
    httpPort: 3000
    noPrependStageInUrl: true

# custom:
  # customDomain:
  #   domainName: api.yourdomain.com   # replace with your subdomain (or root) you wish to use
  #   basePath: ''
  #   stage: ${self:provider.stage}
  #   createRoute53Record: true
